export const REGISTER_STEPS = {
  ACCOUNT_TYPE: 'accountType',
  COUNTRY: 'country',
  ACCOUNT: 'account',
  VERIFY_EMAIL: 'verify-email',
  SET_PASSWORD: 'set-password',
  FEEDBACK: 'feedback',
};

export const REGISTER_CURRENT_STEP = {
  [REGISTER_STEPS.ACCOUNT_TYPE]: REGISTER_STEPS.COUNTRY,
  [REGISTER_STEPS.COUNTRY]: REGISTER_STEPS.ACCOUNT,
  [REGISTER_STEPS.ACCOUNT]: REGISTER_STEPS.VERIFY_EMAIL,
  [REGISTER_STEPS.VERIFY_EMAIL]: REGISTER_STEPS.SET_PASSWORD,
  [REGISTER_STEPS.SET_PASSWORD]: REGISTER_STEPS.FEEDBACK,
  Default: REGISTER_STEPS.COUNTRY,
};
